name: notes
description: A simple Android app for taking notes.

publish_to: 'none'

version: 3.2.7+44

environment:
  sdk: ^3.13.1
  flutter: '3.47.1'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  package_info_plus: ^10.2.1
  shared_preferences: ^2.5.5
  path_provider: ^2.1.6
  url_launcher: ^6.3.2
  flutter_archive: ^6.3.1
  provider: ^6.1.5+1
  file_picker: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true